<# CyberCroc Bar - Google Sheets menu + LAN order/stock queue. #>
Set-StrictMode -Version 2.0
. (Join-Path $PSScriptRoot 'Core.ps1')
function Get-CcBarConfig { $cfg=Get-CcConfig;[pscustomobject]@{SheetId=if($cfg['BAR_SHEET_ID']){[string]$cfg['BAR_SHEET_ID']}else{'1l-p_ck7hS1PmrqJDYAQcni6_boxFK3Pl5BFGqKoMRWM'};Share=[string]$cfg['BAR_SHARE'];Cache=Join-Path $script:CcRoot 'bar-menu.json';Orders=if($cfg['BAR_SHARE']){Join-Path $cfg['BAR_SHARE'] 'bar-orders.json'}else{Join-Path $script:CcRoot 'bar-orders.json'};Stock=if($cfg['BAR_SHARE']){Join-Path $cfg['BAR_SHARE'] 'bar-stock.json'}else{Join-Path $script:CcRoot 'bar-stock.json'};Balances=if($cfg['BAR_SHARE']){Join-Path $cfg['BAR_SHARE'] 'bar-balances.json'}else{Join-Path $script:CcRoot 'bar-balances.json'}} }
function Resolve-CcBarSheetUrl([string]$Url) {
    try {
        if([string]::IsNullOrWhiteSpace($Url)){return ''}
        $u=$Url.Trim()
        if($u -match 'export\\?format=csv' -or $u -match 'gviz/tq'){return $u}
        if($u -match 'docs\\.google\\.com/spreadsheets/d/([^/]+)'){
            $id=$Matches[1];$gid=''
            if($u -match '[?&]gid=(\\d+)'){$gid=$Matches[1]}
            if($gid){return "https://docs.google.com/spreadsheets/d/$id/export?format=csv&gid=$gid"}
            return "https://docs.google.com/spreadsheets/d/$id/export?format=csv"
        }
        return $u
    } catch { Write-CcLog "Google Sheets URL parse failed: $($_.Exception.Message)" 'WARN' 'Resolve-CcBarSheetUrl'; return $Url }
}
function ConvertFrom-CcCsvLine([string]$Line) { $out=@();$cur='';$quote=$false;foreach($ch in $Line.ToCharArray()){if($ch -eq '"'){$quote=-not $quote}elseif($ch -eq ',' -and -not $quote){$out+=$cur;$cur=''}else{$cur+=$ch}};$out+=$cur;return @($out|ForEach-Object{$_.Trim().Trim('"')}) }
function Get-CcBarConfig {
    $cfg=Get-CcConfig;$share=[string]$cfg['BAR_SHARE'];$shareOk=$false;if($share){try{$shareOk=Test-Path -LiteralPath $share -ErrorAction Stop}catch{$shareOk=$false}};$root=$script:CcRoot
    [pscustomobject]@{SheetId=[string]$cfg['BAR_SHEET_ID'];SheetUrl=[string]$cfg['BAR_SHEET_URL'];Share=$share;ShareAvailable=$shareOk;Cache=if($shareOk){Join-Path $share 'bar-menu.json'}else{Join-Path $root 'bar-menu.json'};Orders=if($shareOk){Join-Path $share 'bar-orders.json'}else{Join-Path $root 'bar-orders.json'};Stock=if($shareOk){Join-Path $share 'bar-stock.json'}else{Join-Path $root 'bar-stock.json'};Balances=if($shareOk){Join-Path $share 'bar-balances.json'}else{Join-Path $root 'bar-balances.json'};Prices=if($shareOk){Join-Path $share 'bar-prices.json'}else{Join-Path $root 'bar-prices.json'}}
}
function ConvertFrom-CcCsvLine([string]$Line) {$out=@();$cur='';$quote=$false;foreach($ch in $Line.ToCharArray()){if($ch -eq '"'){$quote=-not $quote}elseif($ch -eq ',' -and -not $quote){$out+=$cur;$cur=''}else{$cur+=$ch}};$out+=$cur;return @($out|ForEach-Object{$_.Trim().Trim('"')})}
function Get-CcBarSeed {
    $rows=@(
      @('Adrenaline 0,449л',0,32),@('Aqua Minerale 0,5л',0,0),@('BonAqua 0,5л',0,0),@('BURN 0,449л',195,38),@('Chillout 0,45л',0,5),@('Cola fresh bar 0,45л',0,8),@('Flash Up Energy 0,45л',0,51),@('Fresh bar 0,45л',0,37),@('Gorilla 0,45л',150,42),@('Lipton 0,5л',0,11),@('Lit energy 0,45л',0,20),@('Rich чай 0,5л',0,38),@('Tornado 0,45л',110,90),@('X-TURBO 0,45',0,4),@('Вода Sensia Fresh',0,32),@('Вода Хрустальная 0,5л',0,3),@('Добрый 0,5л',0,72),@('ПАЛПИ 0,45л',0,32),@('Tornado 1л',0,5),@('Черноголовка 1л',0,7),@('Fresh bar 1,5л',0,9),@('Cheetos 50г',0,19),@('Lay’s 140г',0,9),@('Lay’s 70г',0,5),@('Lay’s из печи 85г',0,17),@('Хрустим Багет 60г',0,0),@('Хруст Nut 80 г',0,6),@('Choco pie',40,40),@('BOUNTY',0,0),@('Bounty Trio',0,3),@('Mars',0,0),@('Mars Max',0,0),@('SNICKERS',0,0),@('Snickers Super',0,3),@('TWIX',0,0),@('TWIX Xtra',0,0),@('Гудмикс 40г',0,0),@('Любятово 50г',0,19),@('Мармелад "GORILLA" 60г',140,9),@('Бельмеши 300гр',0,11),@('Круггетсы 200г',0,6),@('Хотстеры 250гр',0,10),@('Чебупели с ветчиной и сыром 240гр',0,11),@('Чебупели сочные с мясом 240гр',0,11),@('Чебупицца 250гр',0,14),@('Burn',195,38),@('Tornado',110,90),@('Chitos',110,19),@('Chocopai',40,40),@('Gorila en',150,42),@('Gorila мармелад',140,9))
    return @($rows|ForEach-Object{[pscustomobject]@{Name=$_[0];Price=[decimal]$($_[1]);Sku=([string]$_[0]).ToLowerInvariant().Replace(' ','_');StockItem=$_[0];StockQty=1;Category='Бар';Available=$true;Stock=[decimal]$($_[2])}})
}
function Save-CcBarLocalSeed {try{$c=Get-CcBarConfig;if(Test-Path -LiteralPath $c.Cache){return};$items=@(Get-CcBarSeed);$items|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $c.Cache -Encoding UTF8;$stock=@{};foreach($x in $items){$stock[$x.Sku]=[decimal]$x.Stock};$stock|ConvertTo-Json|Set-Content -LiteralPath $c.Stock -Encoding UTF8;Write-CcLog "Bar local seed created: $($items.Count) items" 'OK' 'Save-CcBarLocalSeed'}catch{Write-CcError -FunctionName 'Save-CcBarLocalSeed' -Exception $_.Exception}}
function Get-CcBarMenu {
 try{$c=Get-CcBarConfig;Save-CcBarLocalSeed;$uri=if($c.SheetUrl){Resolve-CcBarSheetUrl $c.SheetUrl}elseif($c.SheetId){"https://docs.google.com/spreadsheets/d/$($c.SheetId)/export?format=csv"}else{''};if($uri){try{$csv=(Invoke-WebRequest -Uri $uri -UseBasicParsing -TimeoutSec 10 -ErrorAction Stop).Content;$rows=@($csv -split '?
'|Where-Object{$_.Trim()});if($rows.Count -ge 2){$head=ConvertFrom-CcCsvLine $rows[0];$result=@();for($i=1;$i -lt $rows.Count;$i++){$v=ConvertFrom-CcCsvLine $rows[$i];$o=@{};for($j=0;$j -lt $head.Count;$j++){if($j -lt $v.Count){$o[$head[$j].Trim().ToLowerInvariant()]=$v[$j]}};if($o['name']){$result+=[pscustomobject]@{Name=[string]$o['name'];Price=[decimal]$(if($o['price']){$o['price']}else{0});Sku=[string]$(if($o['sku']){$o['sku']}else{$o['name']});StockItem=[string]$o['name'];StockQty=1;Stock=[decimal]$(if($o['stock']){$o['stock']}elseif($o['stockqty']){$o['stockqty']}elseif($o['наличие']){$o['наличие']}else{0});Category=[string]$(if($o['category']){$o['category']}else{'Бар'});Available=if($o.ContainsKey('available')){[string]$o['available'] -notin @('0','false','нет')}else{$true}}}};if($result.Count -gt 0){$result|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $c.Cache -Encoding UTF8;Write-CcLog "Bar menu synchronized from Google Sheets: $($result.Count) items" 'OK' 'Get-CcBarMenu'}}}catch{Write-CcLog "Google Sheets unavailable, using local bar cache: $($_.Exception.Message)" 'WARN' 'Get-CcBarMenu'}};$result=@();if(Test-Path -LiteralPath $c.Cache){$result=@(Get-Content -LiteralPath $c.Cache -Raw|ConvertFrom-Json)};if(-not$result -or $result.Count -eq 0){$result=@(Get-CcBarSeed)};if(Test-Path -LiteralPath $c.Prices){$ov=Get-Content -LiteralPath $c.Prices -Raw|ConvertFrom-Json;foreach($m in $result){if($m.Sku -and $ov.PSObject.Properties.Name -contains $m.Sku){$m.Price=[decimal]$ov.($m.Sku)}}};return $result
 }catch{Write-CcError -FunctionName 'Get-CcBarMenu' -Exception $_.Exception;return @(Get-CcBarSeed)}}
function Get-CcBarStock {try{$c=Get-CcBarConfig;Save-CcBarLocalSeed;if(-not(Test-Path -LiteralPath $c.Stock)){return @{}};$j=Get-Content -LiteralPath $c.Stock -Raw|ConvertFrom-Json;$h=@{};foreach($p in $j.PSObject.Properties){$h[$p.Name]=[decimal]$p.Value};return $h}catch{Write-CcError -FunctionName 'Get-CcBarStock' -Exception $_.Exception;return @{}}}
function Save-CcBarStock([hashtable]$Stock){try{$c=Get-CcBarConfig;$Stock|ConvertTo-Json|Set-Content -LiteralPath $c.Stock -Encoding UTF8}catch{Write-CcError -FunctionName 'Save-CcBarStock' -Exception $_.Exception}}
function Get-CcBarOrders {try{$c=Get-CcBarConfig;Save-CcBarLocalSeed;if(-not(Test-Path -LiteralPath $c.Orders)){@()|ConvertTo-Json|Set-Content -LiteralPath $c.Orders -Encoding UTF8};return @(Get-Content -LiteralPath $c.Orders -Raw|ConvertFrom-Json)}catch{Write-CcError -FunctionName 'Get-CcBarOrders' -Exception $_.Exception;return @()}}
function Save-CcBarOrders([object[]]$Orders){try{$c=Get-CcBarConfig;$tmp="$($c.Orders).tmp";@($Orders)|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $tmp -Encoding UTF8;Move-Item -LiteralPath $tmp -Destination $c.Orders -Force}catch{Write-CcError -FunctionName 'Save-CcBarOrders' -Exception $_.Exception;throw}}
function Get-CcBarBalances {try{$c=Get-CcBarConfig;Save-CcBarLocalSeed;if(-not(Test-Path -LiteralPath $c.Balances)){@{}|ConvertTo-Json|Set-Content -LiteralPath $c.Balances -Encoding UTF8};$j=Get-Content -LiteralPath $c.Balances -Raw|ConvertFrom-Json;$h=@{};foreach($p in $j.PSObject.Properties){$h[$p.Name]=[decimal]$p.Value};return $h}catch{Write-CcError -FunctionName 'Get-CcBarBalances' -Exception $_.Exception;return @{}}}
function Save-CcBarBalances([hashtable]$Balances){try{$c=Get-CcBarConfig;$Balances|ConvertTo-Json|Set-Content -LiteralPath $c.Balances -Encoding UTF8}catch{Write-CcError -FunctionName 'Save-CcBarBalances' -Exception $_.Exception}}
function Set-CcBarBalance([string]$Pc,[decimal]$Balance){$h=Get-CcBarBalances;$h[$Pc]=$Balance;Save-CcBarBalances $h;return $true}
function New-CcBarOrder([string]$Pc,[object]$Item,[decimal]$Qty=1){try{$orders=@(Get-CcBarOrders);$o=[pscustomobject]@{Id=[guid]::NewGuid().ToString();Pc=$Pc;Item=$Item.Name;Sku=$Item.Sku;Qty=$Qty;UnitPrice=[decimal]$Item.Price;Total=[decimal]$Item.Price*$Qty;Status='Pending';Created=(Get-Date).ToString('s')};$orders+=$o;Save-CcBarOrders $orders;Write-CcLog "Bar order created: $($o.Id) PC=$Pc item=$($o.Item)" 'INFO' 'New-CcBarOrder';return $o}catch{Write-CcError -FunctionName 'New-CcBarOrder' -Exception $_.Exception;return $null}}
function Confirm-CcBarOrder([string]$Id){try{$orders=@(Get-CcBarOrders);$o=$orders|Where-Object Id -eq $Id|Select-Object -First 1;if(-not$o){throw "Order not found: $Id"};if($o.Status -ne 'Pending'){throw "Order status is $($o.Status)"};$balances=Get-CcBarBalances;$pc=[string]$o.Pc;$balance=if($balances.ContainsKey($pc)){[decimal]$balances[$pc]}else{0};if($balance -lt [decimal]$o.Total){throw "Недостаточно средств на балансе ПК ${pc}: $balance"};$stock=Get-CcBarStock;if($o.Sku -and $stock.ContainsKey($o.Sku)){$need=[decimal]$o.Qty;if($stock[$o.Sku] -lt $need){throw "Недостаточно товара на складе: $($o.Sku)"};$stock[$o.Sku]-=$need;Save-CcBarStock $stock};$balances[$pc]=$balance-[decimal]$o.Total;Save-CcBarBalances $balances;$o.Status='Confirmed';$o.Confirmed=(Get-Date).ToString('s');Save-CcBarOrders $orders;Write-CcLog "Bar order confirmed: $Id total=$($o.Total)" 'OK' 'Confirm-CcBarOrder';return $o}catch{Write-CcError -FunctionName 'Confirm-CcBarOrder' -Exception $_.Exception;return $null}}
function Reject-CcBarOrder([string]$Id){try{$orders=@(Get-CcBarOrders);$o=$orders|Where-Object Id -eq $Id|Select-Object -First 1;if(-not$o){throw "Order not found: $Id"};$o.Status='Rejected';Save-CcBarOrders $orders;Write-CcLog "Bar order rejected: $Id" 'WARN' 'Reject-CcBarOrder';return $true}catch{Write-CcError -FunctionName 'Reject-CcBarOrder' -Exception $_.Exception;return $false}}
function Set-CcBarPrice([string]$Sku,[decimal]$Price){try{if([string]::IsNullOrWhiteSpace($Sku)){throw 'SKU не указан.'};if($Price -lt 0){throw 'Цена не может быть отрицательной.'};$c=Get-CcBarConfig;$h=@{};if(Test-Path -LiteralPath $c.Prices){$j=Get-Content -LiteralPath $c.Prices -Raw|ConvertFrom-Json;foreach($p in $j.PSObject.Properties){$h[$p.Name]=$p.Value}};$h[$Sku]=$Price;$h|ConvertTo-Json|Set-Content -LiteralPath $c.Prices -Encoding UTF8;Write-CcLog "Bar price override: $Sku=$Price" 'OK' 'Set-CcBarPrice';return $true}catch{Write-CcError -FunctionName 'Set-CcBarPrice' -Exception $_.Exception;return $false}}
