<# CyberCroc Bar - Google Sheets menu + LAN order/stock queue. #>
Set-StrictMode -Version 2.0
. (Join-Path $PSScriptRoot 'Core.ps1')
function Get-CcBarConfig { $cfg=Get-CcConfig;[pscustomobject]@{SheetId=if($cfg['BAR_SHEET_ID']){[string]$cfg['BAR_SHEET_ID']}else{'1l-p_ck7hS1PmrqJDYAQcni6_boxFK3Pl5BFGqKoMRWM'};Share=[string]$cfg['BAR_SHARE'];Cache=Join-Path $script:CcRoot 'bar-menu.json';Orders=if($cfg['BAR_SHARE']){Join-Path $cfg['BAR_SHARE'] 'bar-orders.json'}else{Join-Path $script:CcRoot 'bar-orders.json'};Stock=if($cfg['BAR_SHARE']){Join-Path $cfg['BAR_SHARE'] 'bar-stock.json'}else{Join-Path $script:CcRoot 'bar-stock.json'};Balances=if($cfg['BAR_SHARE']){Join-Path $cfg['BAR_SHARE'] 'bar-balances.json'}else{Join-Path $script:CcRoot 'bar-balances.json'}} }
function ConvertFrom-CcCsvLine([string]$Line) { $out=@();$cur='';$quote=$false;foreach($ch in $Line.ToCharArray()){if($ch -eq '"'){$quote=-not $quote}elseif($ch -eq ',' -and -not $quote){$out+=$cur;$cur=''}else{$cur+=$ch}};$out+=$cur;return @($out|ForEach-Object{$_.Trim().Trim('"')}) }
function Get-CcBarMenu { try { $c=Get-CcBarConfig;$uri="https://docs.google.com/spreadsheets/d/$($c.SheetId)/export?format=csv";$csv=(Invoke-WebRequest -Uri $uri -UseBasicParsing -TimeoutSec 15 -ErrorAction Stop).Content;$rows=@($csv -split "`r?`n"|Where-Object{$_.Trim()});if($rows.Count -lt 2){throw 'Google Sheet пуст или не содержит строки меню.'};$head=ConvertFrom-CcCsvLine $rows[0];$result=@();for($i=1;$i -lt $rows.Count;$i++){$v=ConvertFrom-CcCsvLine $rows[$i];$o=@{};for($j=0;$j -lt $head.Count;$j++){if($j -lt $v.Count){$o[$head[$j].Trim().ToLowerInvariant()]=$v[$j]}};if($o['name']){$result+=[pscustomobject]@{Name=[string]$o['name'];Price=[decimal]$(if($o['price']){$o['price']}else{0});Sku=[string]$o['sku'];StockItem=[string]$o['stockitem'];StockQty=[decimal]$(if($o['stockqty']){$o['stockqty']}else{1});Category=[string]$o['category'];Available=if($o.ContainsKey('available')){[string]$o['available'] -notin @('0','false','нет')}else{$true}}}};$result|ConvertTo-Json -Depth 6|Set-Content -LiteralPath $c.Cache -Encoding UTF8;Write-CcLog "Bar menu loaded: $($result.Count)" 'OK' 'Get-CcBarMenu';return $result } catch { Write-CcError -FunctionName 'Get-CcBarMenu' -Exception $_.Exception;$c=Get-CcBarConfig;if(Test-Path $c.Cache){return @(Get-Content $c.Cache -Raw|ConvertFrom-Json)};return @() } }
function Get-CcBarStock { try{$c=Get-CcBarConfig;if(-not(Test-Path $c.Stock)){@{}|ConvertTo-Json|Set-Content $c.Stock -Encoding UTF8};$j=Get-Content $c.Stock -Raw|ConvertFrom-Json;$h=@{};foreach($p in $j.PSObject.Properties){$h[$p.Name]=[decimal]$p.Value};return $h}catch{Write-CcError -FunctionName 'Get-CcBarStock' -Exception $_.Exception;return @{}} }
function Save-CcBarStock([hashtable]$Stock){$c=Get-CcBarConfig;$Stock|ConvertTo-Json|Set-Content $c.Stock -Encoding UTF8}
function Get-CcBarOrders { try{$c=Get-CcBarConfig;if(-not(Test-Path $c.Orders)){@()|ConvertTo-Json|Set-Content $c.Orders -Encoding UTF8};return @(Get-Content $c.Orders -Raw|ConvertFrom-Json)}catch{Write-CcError -FunctionName 'Get-CcBarOrders' -Exception $_.Exception;return @()}}
function Save-CcBarOrders([object[]]$Orders){$c=Get-CcBarConfig;$tmp="$($c.Orders).tmp";@($Orders)|ConvertTo-Json -Depth 8|Set-Content $tmp -Encoding UTF8;Move-Item $tmp $c.Orders -Force}
function Get-CcBarBalances { try{$c=Get-CcBarConfig;if(-not(Test-Path $c.Balances)){@{}|ConvertTo-Json|Set-Content $c.Balances -Encoding UTF8};$j=Get-Content $c.Balances -Raw|ConvertFrom-Json;$h=@{};foreach($p in $j.PSObject.Properties){$h[$p.Name]=[decimal]$p.Value};return $h}catch{Write-CcError -FunctionName 'Get-CcBarBalances' -Exception $_.Exception;return @{}} }
function Save-CcBarBalances([hashtable]$Balances){$c=Get-CcBarConfig;$Balances|ConvertTo-Json|Set-Content $c.Balances -Encoding UTF8}
function Set-CcBarBalance([string]$Pc,[decimal]$Balance){$h=Get-CcBarBalances;$h[$Pc]=$Balance;Save-CcBarBalances $h;return $true}
function New-CcBarOrder([string]$Pc,[object]$Item,[decimal]$Qty=1){try{$orders=@(Get-CcBarOrders);$o=[pscustomobject]@{Id=[guid]::NewGuid().ToString();Pc=$Pc;Item=$Item.Name;Sku=$Item.Sku;Qty=$Qty;UnitPrice=[decimal]$Item.Price;Total=[decimal]$Item.Price*$Qty;Status='Pending';Created=(Get-Date).ToString('s')};$orders+=$o;Save-CcBarOrders $orders;Write-CcLog "Bar order created: $($o.Id) PC=$Pc item=$($o.Item)" 'INFO' 'New-CcBarOrder';return $o}catch{Write-CcError -FunctionName 'New-CcBarOrder' -Exception $_.Exception;return $null}}
function Confirm-CcBarOrder([string]$Id){try{$orders=@(Get-CcBarOrders);$o=$orders|Where-Object Id -eq $Id|Select-Object -First 1;if(-not$o){throw "Order not found: $Id"};if($o.Status -ne 'Pending'){throw "Order status is $($o.Status)"};$balances=Get-CcBarBalances;$pc=[string]$o.Pc;$balance=if($balances.ContainsKey($pc)){[decimal]$balances[$pc]}else{0};if($balance -lt [decimal]$o.Total){throw "Недостаточно средств на балансе ПК $pc: $balance"};$stock=Get-CcBarStock;if($o.Sku -and $stock.ContainsKey($o.Sku)){$need=[decimal]$o.Qty;if($stock[$o.Sku] -lt $need){throw "Недостаточно товара на складе: $($o.Sku)"};$stock[$o.Sku]-=$need;Save-CcBarStock $stock};$balances[$pc]=$balance-[decimal]$o.Total;Save-CcBarBalances $balances;$o.Status='Confirmed';$o.Confirmed=(Get-Date).ToString('s');Save-CcBarOrders $orders;Write-CcLog "Bar order confirmed: $Id total=$($o.Total)" 'OK' 'Confirm-CcBarOrder';return $o}catch{Write-CcError -FunctionName 'Confirm-CcBarOrder' -Exception $_.Exception;return $null}}
function Reject-CcBarOrder([string]$Id){try{$orders=@(Get-CcBarOrders);$o=$orders|Where-Object Id -eq $Id|Select-Object -First 1;if(-not$o){throw "Order not found: $Id"};$o.Status='Rejected';Save-CcBarOrders $orders;Write-CcLog "Bar order rejected: $Id" 'WARN' 'Reject-CcBarOrder';return $true}catch{Write-CcError -FunctionName 'Reject-CcBarOrder' -Exception $_.Exception;return $false}}
function Set-CcBarPrice([string]$Sku,[decimal]$Price){try{$override=Join-Path $script:CcRoot 'bar-prices.json';$h=@{};if(Test-Path $override){$j=Get-Content $override -Raw|ConvertFrom-Json;foreach($p in $j.PSObject.Properties){$h[$p.Name]=$p.Value}};$h[$Sku]=$Price;$h|ConvertTo-Json|Set-Content $override -Encoding UTF8;Write-CcLog "Bar price override: $Sku=$Price" 'OK' 'Set-CcBarPrice';return $true}catch{Write-CcError -FunctionName 'Set-CcBarPrice' -Exception $_.Exception;return $false}}