<## CyberCroc Games - SMB game catalog and patch management. PowerShell 5.1 compatible. ##>
Set-StrictMode -Version 2.0
. (Join-Path $PSScriptRoot 'Core.ps1')
function Get-CcGamesConfig { try { $cfg=Get-CcConfig; [pscustomobject]@{Share=[string]$cfg['GAMES_SHARE'];Cache=Join-Path $script:CcRoot 'games-cache.json'} } catch { Write-CcError -FunctionName 'Get-CcGamesConfig' -Exception $_.Exception; return [pscustomobject]@{Share='';Cache=(Join-Path $script:CcRoot 'games-cache.json')} } }
function Convert-CcGameRecord([object]$Game) { [pscustomobject]@{Id=[string]$Game.Id;Name=[string]$Game.Name;InstallPath=[string]$Game.InstallPath;Launcher=[string]$Game.Launcher;AppId=[string]$Game.AppId;LatestPatch=[string]$Game.LatestPatch;Source=[string]$Game.Source;SizeGB=if($Game.SizeGB){[double]$Game.SizeGB}else{0}} }
function Get-CcGamesFromJson([string]$Path) { try { if(-not(Test-Path -LiteralPath $Path)){throw "games.json not found: $Path"};$json=Get-Content -LiteralPath $Path -Raw -Encoding UTF8|ConvertFrom-Json;$items=if($json.Games){@($json.Games)}else{@($json)};return @($items|ForEach-Object{Convert-CcGameRecord $_}) } catch { Write-CcError -FunctionName 'Get-CcGamesFromJson' -Exception $_.Exception;return @() } }
function Get-CcGamesCatalog([switch]$ForceRefresh) { try { $c=Get-CcGamesConfig;$remote=if($c.Share){Join-Path $c.Share 'games.json'}else{''};if($remote -and (Test-Path -LiteralPath $remote) -and ($ForceRefresh -or -not(Test-Path -LiteralPath $c.Cache) -or (Get-Item $remote).LastWriteTimeUtc -gt (Get-Item $c.Cache).LastWriteTimeUtc)){ $items=Get-CcGamesFromJson $remote;if($items.Count){$items|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $c.Cache -Encoding UTF8;Write-CcLog "Games catalog pulled from SMB: $remote ($($items.Count))" 'OK' 'Get-CcGamesCatalog';return $items}};if(Test-Path -LiteralPath $c.Cache){return @(Get-CcGamesFromJson $c.Cache)};return @() } catch { Write-CcError -FunctionName 'Get-CcGamesCatalog' -Exception $_.Exception;return @() } }
function Get-CcGameStatus([object]$Game) { try { $path=Expand-CcPath $Game.InstallPath;$installed=Test-Path -LiteralPath $path;$installedPatch='';$marker=Join-Path $path 'cybercroc.patch';if($installed -and (Test-Path -LiteralPath $marker)){$installedPatch=(Get-Content $marker -Raw -ErrorAction SilentlyContinue).Trim()};if(-not $installed){$installedPatch='Not installed'};$state=if(-not $installed){'NotInstalled'}elseif($Game.LatestPatch -and $installedPatch -ne [string]$Game.LatestPatch){'UpdateRequired'}else{'Latest'};return [pscustomobject]@{Id=$Game.Id;Name=$Game.Name;Installed=$installed;LatestPatch=[string]$Game.LatestPatch;InstalledPatch=$installedPatch;Status=$state} } catch { Write-CcError -FunctionName 'Get-CcGameStatus' -Exception $_.Exception;return [pscustomobject]@{Id=$Game.Id;Name=$Game.Name;Installed=$false;LatestPatch=[string]$Game.LatestPatch;InstalledPatch='Error';Status='Error'} } }
function Install-CcGame { param([object]$Game) try { $c=Get-CcGamesConfig;if([string]::IsNullOrWhiteSpace($c.Share)){throw 'GAMES_SHARE не задан в config.ini'};$source=if($Game.Source){Expand-CcPath ([string]$Game.Source)}else{Join-Path $c.Share $Game.Id};if(-not(Test-Path -LiteralPath $source)){throw "Источник игры не найден: $source"};$dest=Expand-CcPath $Game.InstallPath;if([string]::IsNullOrWhiteSpace($dest)){throw "InstallPath не задан для $($Game.Name)"};New-Item -ItemType Directory -Path $dest -Force|Out-Null;& robocopy.exe $source $dest /E /COPY:DAT /DCOPY:DAT /R:2 /W:1 /NP /NFL /NDL /NJH /NJS|Out-Null;$rc=$LASTEXITCODE;if($rc -ge 8){throw "Robocopy failed with code $rc"};if($Game.LatestPatch){Set-Content -LiteralPath (Join-Path $dest 'cybercroc.patch') -Value $Game.LatestPatch -Encoding ASCII};Write-CcLog "Game installed/updated: $($Game.Name), patch=$($Game.LatestPatch)" 'OK' 'Install-CcGame';return $true } catch { Write-CcError -FunctionName 'Install-CcGame' -Exception $_.Exception;return $false } }
function Update-CcGame([object]$Game) { return Install-CcGame $Game }
function Update-CcGamesCatalogDaily { try { $marker=Join-Path $script:CcRoot 'games-sync.txt';$today=(Get-Date).ToString('yyyy-MM-dd');$last=if(Test-Path $marker){(Get-Content $marker -Raw).Trim()}else{''};if($last -ne $today){$items=Get-CcGamesCatalog -ForceRefresh;Set-Content -LiteralPath $marker -Value $today -Encoding ASCII;return $items};return @(Get-CcGamesCatalog) } catch { Write-CcError -FunctionName 'Update-CcGamesCatalogDaily' -Exception $_.Exception;return @() } }